pkg/db/migrate/files/202006021731.sql, pkg/db/oidc_requests.go, pkg/db/oidc_requests_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
closes #30 
depends on #31 
A specific OIDC request record is pulled from the DB by the EndUser target, the Relying Party that made it (clientID), and the scopes requested.
Field `scopes_hash` is transparently added to `oidc_request` with the hash of the array of scopes and indexed. This sets a max upper bound on the width of the datatype, allowing for efficient indexing.
=> chore: triangulate specific oidc_request by sub, clientID, and scopes

cmd/adapter-rest/startcmd/start.go, go.mod, pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: Issuer multi-tenancy support

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
This PR:
* enables the RP adapter to handle OAuth2 client registration at Hydra on behalf of the RP tenant, returning the ClientID and ClientSecret in the response (note: the ClientSecret is not stored by the RP Adapter)
* Removes test dependencies on MySQL in order to gain a few developer cycles. The relevant code was left unused.
closes #71 
closes #44
=> feat: rp adapter creates oauth2 client at hydra

cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/vc/models.go, pkg/vc/rp/models.go
closes #120 
closes #121 
* #120: rp adapter:
* embed issuer's and rp's did docs in the consent VC
* chapiResponseHandler now expects a VP (presentation_submission)
with a single VC (the user's consent VC)
* #121: rp adapter: refactor CHAPI request
<details><summary>Example of a CHAPI request:</summary>
<p>
```javascript
{
web: {
VerifiablePresentation: {
query: [
{
type: "presentationDefinitionQuery",
presentationDefinitionQuery: {
"input_descriptors": [
{
"id": "banking_input_1",
"group": ["scope1"],
"schema": {
"uri": "https://bank-standards.com/customer.json",
"name": "Bank Account Information",
"purpose": "We need your bank and account information."
}
}
]
}
},
{
type: "DIDComm",
invitation: {
"@id": "123456",
"@type": "https://didcomm.org/didexchange/1.0/invitation",
"label": "RP's …
```
=> refactor: #120 and #121

pkg/internal/mock/connection/connection_lookup.go, pkg/internal/mock/didexchange/client.go, pkg/internal/mock/presentproof/client.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/go.mod, test/bdd/pkg/rp/rp_steps.go
closes #137 
This PR includes fixes 2 and 3 as well:
1. makes the RP adapter use explicit didexchange invitations instead of implicit ones using the RP tenant's public DID
2. fix: missing callback url when registering rp tenants
3. fix: user subject is empty when the user has not "logged in" yet with the adapter
4. moves the mock didexchange client to its own package
=> refactor: #137 rp adapter: use explicit didcomm invitations

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/healthcheck_api.feature, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/pkg/rp/rp_steps.go
fixes #187
- remove openid scope from the input to the presentations-definitions provider
- fix SSL_ERROR_RX_RECORD_TOO_LONG on firefox (on chrome the error is different) by serving HTTPS
- incorrect wallet data sent to the backend for evaluation
- configure publickeyfetcher when parsing verifiable credential from wallet
=> fix: #187 rp-adapter: various fixes

cmd/adapter-rest/startcmd/start.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/agent/agent_controller_steps.go
- Update request format in present proof request
- Create http client from the options in issuer adapter
closes #190 
=> refactor: [Issuer Adapter] Expect VP instead of VC in presentation request

pkg/restapi/rp/operation/operations.go
fixes #197
The `verifiable.PublicKeyFetcher` option was not being passed in to `verifiable.ParseCredential()`
=> fix: #197 rp-adapter: error while parsing VC from issuer

Makefile, images/adapter-rest-base/Dockerfile, images/issuer-adapter-rest/Dockerfile, images/rp-adapter-rest/Dockerfile
* GO_VER and ALPINE_VER bumped up to 1.14.6 and 3.12 respectively
* Separate make recipe for base adapter docker image
* Use host to build Vue sites
Comparisons:
Old:
```
$ time make rp-adapter-rest-docker issuer-adapter-rest-docker
....
real    3m42.125s
user    0m4.139s
sys     0m2.639s
```
New:
```
$ time make rp-adapter-rest-docker issuer-adapter-rest-docker
....
real    1m59.907s
user    0m44.375s
sys     0m5.544s
```
Size of images remain the same at roughly 33MB.
=> fix: slow image build times

cmd/adapter-rest/startcmd/start.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/restapi/rp/operation/transient_data.go
closes #29 
This PR:
* Deletes `invitationData` and `thidInvitationData`
* Renames `consentRequest` -> `consentRequestCtx`. It is active right up to the point when the CHAPI request is delivered to the frontend. Stored in transient storage.
* Adds `walletResponseCtx` which replaces use of `invitationData` and `thidInvitationData` in some places. It remains stored in memory because it is active from the moment the wallet response is received (meaning there is an active network socket between the backend and the user agent) to the moment the user is redirected to Hydra.
The `oidcStates` in-memory structure was left untouched as that is referenced solely from the currently unused `hydraLoginHandler()` method. This method is likely to be refactored or deleted altogether anyway once we …
=> refactor: rpadapter: #29 use transient storage

cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/presexch/api.go, pkg/presexch/api_test.go, scripts/check_license.sh, test/bdd/go.sum
This is a temporary solution.
The existing models in the `presentationex` package will be removed in task #234
closes #239 
This PR also fixes a typo in `check_license.sh`
=> chore: copy aries framework presentation-exchange API

pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/api.go, test/bdd/cmd/issuer/go.mod, test/bdd/cmd/issuer/go.sum, test/bdd/cmd/issuer/main.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/issuer/issuer_steps.go
- New option while creating the profile
- CHAPI Request contains Reference VC and Manifest of Assurance VC along with DIDConnect Invitation
- New Issuer API to fetch assurance data
closes #260 
=> feat: Support for Credential with Assurance Credential flow

pkg/presentationex/provider.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/pkg/rp/rp_steps.go
closes #277 
The RP Adapter now returns OIDC aggregate claims, where each claim source object is a `verified_claims` element:
https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html#section-5.
Each member name of `_claim_names` is one of the requested scopes. These do not include [standard OIDC scopes](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims). These are likely to be included as standard top-level claims once user SSO authentication is implemented. 
Each value of `_claim_sources` is a `verified_claims` object. This is different than standard OIDC [aggregate && distributed claims](https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims) because the spec mandates these objects be JWTs (for aggregate claims). The RP Adapter …
=> refactor: #277 rp-adapter id_token response

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go
The manifest is being part of 'credentials' attribute.
closes #281 
=> refactor: [Issuer Adapter] Remove 'manifest' attribute in chapi request

Makefile, README.md, ci/azure-pipelines.yml, cmd/adapter-rest/go.mod, cmd/adapter-rest/startcmd/start.go, docs/build.md, go.mod, test/bdd/cmd/issuer/go.mod, test/bdd/go.mod
- Upgrade to Go v1.15
- Build document
- Link from README to build doc
part of #324 
=> chore: Upgrade to Go v1.15 and build documentation

.dockerignore
Added dockerignore file to skip npm_modules passed to docker build context. The npm_modules for RP and Issuer adapter VUE folder size is around 250MB each. Skipping these improves the docker build time.
In CI, the build time improvements is around 50% (~6min vs ~9min).
Master Build - https://dev.azure.com/trustbloc/edge/_build/results?buildId=8377&view=results
This PR Build - https://dev.azure.com/trustbloc/edge/_build/results?buildId=8378&view=logs&j=888c3ba9-6bd0-5e3d-cb39-2cba9e4c5cc5
=> chore: Add dockerignore to skip npm_modules in build context

pkg/aries/api.go, pkg/restapi/internal/mocks/protocol/outofband.go, pkg/restapi/internal/mocks/provider/provider.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/restapi/wallet/controller.go, pkg/restapi/wallet/controller_test.go, pkg/restapi/wallet/operation/models.go, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go, pkg/restapi/wallet/operation/store.go, pkg/restapi/wallet/operation/store_test.go
- migrated from
https://github.com/trustbloc/edge-agent/tree/main/pkg/restapi/wallet/chapibridge
- part of #413
- part of https://github.com/trustbloc/edge-agent/issues/651
- TODO: to be part of cmd/adapter-rest in next PR
=> feat: wallet-bridge operations

pkg/restapi/issuer/operation/operations.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
Governance credential issuance will fail if retried for a profile,
so it needs to be done last so a subsequent failure won't cause
the profile creation to deadlock.
=> fix: issue governance credential as final step of profile creation

pkg/db/rp/models.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
This flag will be used to switch between WACI and non-waci (existing) flow.
closes #501 
=> chore: Verifier profile -  Add supportsWACI configuration

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/rp_steps.go
Verifier adapter support to
- handle present-proof propose message
- send present-proof request message
- handle present-proof presentation message
- send present-proof presentation message
part of #502 
=> feat: hooks to implement WACI flow

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go
=> fix: skip manifest file read if not set

cmd/adapter-rest/startcmd/start.go, pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
=> feat: [WACI-Issuance] Support to read credential manifest

docs/issuer/integration/issuer.md, docs/rp/integration/relying_parties.md
=> docs: rp/issuer adapter and rp/issuer integration flow diagram

.github/workflows/build.yml, cmd/adapter-rest/startcmd/start.go, docs/build.md, test/bdd/features/rp_e2e.feature, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/integration/docker-compose.yml, test/bdd/fixtures/testdata/contexts/test-contexts.json, test/bdd/fixtures/testdata/presentationdefinitions.json, test/bdd/pkg/rp/rp_steps.go
- Add HTTPS Support for DIDComm Inbound port
- Add prc card scope in RP adapter
- Add citizenship json-ld context
closes #303 
=> fix: HTTPS Support for DIDComm Inbound port

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/features/waci_didcommv2.feature, test/bdd/fixtures/testdata/manifest-config/cmdescriptors.json, test/bdd/pkg/agent/testdata/vc_prc.json, test/bdd/pkg/agent/wallet.go
=> feat: Add [waci-issuance] bdd tests

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/memcmdescriptor/provider.go, pkg/memcmdescriptor/provider_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
=> fix: Refactor credential manifest output descriptors

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start_test.go, cmd/adapter-rest/startcmd/testdata/outputdescriptors.json, go.mod, go.sum, pkg/memcmdescriptor/provider.go, pkg/memcmdescriptor/provider_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/fixtures/testdata/manifest-config/cmdescriptors.json, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/agent/testdata/vc_prc.json, test/bdd/pkg/agent/wallet.go
=> feat: Update to latest aries and support for submission requirement
