trustbloc/adapter

Makefile, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, cmd/adapter-vue/.gitignore, cmd/adapter-vue/README.md, cmd/adapter-vue/babel.config.js, cmd/adapter-vue/package-lock.json, cmd/adapter-vue/package.json, cmd/adapter-vue/public/index.html, cmd/adapter-vue/src/App.vue, cmd/adapter-vue/src/assets/.gitkeep, cmd/adapter-vue/src/components/Credentials.vue, cmd/adapter-vue/src/main.js, cmd/adapter-vue/vue.config.js, images/adapter-rest/Dockerfile, test/bdd/fixtures/adapter-rest/.env, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> chore: #6 setup project

Makefile, images/adapter-rest/Dockerfile
=> chore: build adapter vue inside image

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, go.mod, go.sum, pkg/internal/common/support/httphandler.go, pkg/internal/common/support/httphandler_test.go, pkg/restapi/rp/controller.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, scripts/check_lint.sh
=> chore: Create rest api for rp adapter

cmd/adapter-rest/startcmd/start.go, pkg/restapi/healthcheck/controller.go, pkg/restapi/healthcheck/controller_test.go, pkg/restapi/healthcheck/operation/operations.go, pkg/restapi/healthcheck/operation/operations_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> chore: Add health check rest api

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/presentationex/api.go, pkg/presentationex/provider.go, pkg/presentationex/provider_test.go, pkg/restapi/internal/common/http/common.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/testdata/presentationdefinitions.json
=> feat: Map OIDC scope to Presentation Exchange

ci/version_var.sh
=> fix: docker image name

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> feat: support parsing driverName from DSN

cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json, cmd/rp-adapter-vue/src/App.vue, cmd/rp-adapter-vue/src/components/.gitkeep, cmd/rp-adapter-vue/src/main.js, cmd/rp-adapter-vue/src/pages/Credentials.vue, cmd/rp-adapter-vue/src/pages/PageNotFound.vue, cmd/rp-adapter-vue/src/pages/layout/Footer.vue, cmd/rp-adapter-vue/src/pages/layout/Layout.vue, cmd/rp-adapter-vue/src/router/index.js
=> chore: refactor rp-adapter-vue

cmd/rp-adapter-vue/src/main.js, cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/operation/operations.go
=> feat: #36 rp frontend fetches presentation-request and sends via CHAPI

cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/db/migrate/files/202006021731.sql, pkg/db/oidc_requests_test.go, pkg/db/relying_parties.go, pkg/db/relying_parties_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: #51 deliver rp public DID to wallet

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> fix: set ui endpoint in issuer ops

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> feat: #54 RP adapter: didcomm connection establishment with wallet

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
closes #64
The hydra login endpoint was bound to new handler `hydraLoginHandlerIterOne` that does not perform user authentication.
This PR fulfills steps 1->3 described in #64. The rest are fulfilled by the existing handler `hydraConsentHandler`.
=> refactor: #64 RP adapter short-circuit user authentication

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: Integrate issuer profile with wallet connect API

cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, go.mod, go.sum, pkg/aries/api.go, pkg/did/trustbloc_did_creator.go, pkg/did/trustbloc_did_creator_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> feat: #67 rp adapter creates public DIDs for tenants

pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> refactor: Move issuer profile create logic out of operations

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: Validate Wallet response API

go.mod, pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/testdata/context/trustbloc_example.jsonld, pkg/vc/models.go, pkg/vc/rp/models.go, scripts/check_license.sh
=> feat: #84 rp adapter: parse vp from CHAPI response

pkg/internal/common/adapterutil/adapterutil.go, pkg/internal/common/adapterutil/adapterutil_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/credentials.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/issuer/models.go, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: Issuer Adapter - Validate Wallet Connect Response

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, pkg/internal/common/adapterutil/adapterutil.go, pkg/internal/common/adapterutil/adapterutil_test.go, pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/issuer/issuer_steps.go
=> feat: Issuer adapter - support issuer callback after wallet connect

cmd/adapter-rest/startcmd/start.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: #86 create RP-Issuer connection record

pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, test/bdd/features/healthcheck_api.feature, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/pkg/issuer/issuer_steps.go
=> refactor: Issuer Adapter - Update DIDConnection VC type and added disabled VC proof check

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
=> refactor: Issuer adapter - UI update to add redirect link to issuer

pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/go.mod, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] Support for state value between issuer and adapter redirects

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: #94 capture rp peer DID after connection complete with user

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] Add mapping between token and connectionID

pkg/internal/mock/issuecredential/service.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go
=> feat: [Issuer Adapter] Support for issue credential protocol

pkg/aries/api.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/issuer/models.go, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/bddutil/util.go
- VC with Issuer DIDDoc returned to wallet
closes #125 
=> feat: [Issuer Adapter] DIDCommInit Credential return to wallet

cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: #130 rp adapter: return data to the rp

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/internal/mock/issuecredential/service.go, test/bdd/fixtures/didcomm/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update aries framework go version

pkg/internal/mock/presentproof/client.go, pkg/internal/mock/presentproof/service.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go
=> feat: [Issuer Adapter] Support for present proof protocol

pkg/restapi/rp/operation/operations.go, test/bdd/features/rp_e2e.feature, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/didcomm/.env, test/bdd/fixtures/didcomm/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/rp_steps.go
=> test: #132 rp adapter: bdd test for didexchange with wallet

pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
fixes #142 
depends on #144 
Request to the issuer adapter:
```json
{
"@id": "12345",
"@type": "https://didcomm.org/present-proof/2.0/request-presentation",
"formats": [{
"attach_id": "123",
"format": "trustbloc/UserConsentVerifiableCredential@0.1.0",
}],
"request_presentations~attach": [{
"@id": "123",
"mime-type": "application/ld+json",
"data": {
"base64": "base64Encode(vp with user consent VC)"
}
}]
}
```
=> fix: #142 rp adapter: send consent VC to issuer adapter

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/issuer/models.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] Include manifest in CHAPI request to wallet

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/models.go, test/bdd/pkg/agent/agent_controller_steps.go
=> refactor: [Issuer Adapter] Update Consent Credential Model

pkg/restapi/internal/common/http/common.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, test/bdd/pkg/agent/agent_controller_steps.go
=> feat: [Issuer Adapter] Validate Consent Credential in Request presentation flow

Makefile, images/mock/issuer/Dockerfile, pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/cmd/issuer/main.go, test/bdd/features/issuer_e2e.feature, test/bdd/fixtures/integration/.env, test/bdd/fixtures/integration/docker-compose.yml, test/bdd/go.mod, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] Create Presentation with User Data

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/agent/agent_controller_steps.go
=> feat: [Issuer Adapter] Create connection record with RP from consent cred request

cmd/rp-adapter-vue/src/pages/Credentials.vue
=> feat: #165 rp adapter: redirect user back to rp renant

cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/aries/api.go, pkg/crypto/crypto.go, pkg/crypto/crypto_test.go, pkg/crypto/util.go, pkg/did/trustbloc_did_creator.go, pkg/internal/mock/diddoc/diddoc.go, pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/api.go, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/pkg/agent/agent_controller_steps.go
- DID Creation for issuer profile
- VC/VP Signing APIs
- Sign User Data presentation (sent to rp)
closes #170 
=> feat: Support for VC/VP Signing

cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/did/trustbloc_did_creator.go, test/bdd/fixtures/did-trustbloc/.env, test/bdd/go.mod, test/bdd/go.sum
and corresponding libraries
Closes #173
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
=> chore: Update sidetree/did-method/vc-rest images

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, test/bdd/go.mod, test/bdd/go.sum
- Update the edge-core dependency
- Add name to Manifest VC
closes #175 
=> feat: [Issuer Adapter] Add Issuer name to the Manifest VC

cmd/rp-adapter-vue/src/pages/Credentials.vue
=> fix: rp-adapter-vue: unhandled promise when fetching CHAPI request from backend

cmd/rp-adapter-vue/src/pages/Credentials.vue
fixes #171 
Also improper handling of http call to the backend to handle the chapi response
=> fix: #171 rp-adapter: query types in CHAPI request

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/did/trustbloc_did_creator.go, pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/testdata/context/consent-credential-v1.jsonld, pkg/vc/issuer/credentials.go, pkg/vc/models.go, test/bdd/fixtures/didcomm/.env, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/context/context.go, test/bdd/pkg/rp/testdata/context/consent-credential-v1.jsonld
=> feat: [Issuer Adapter] Sign Consent Credential

cmd/adapter-rest/startcmd/start.go, pkg/did/trustbloc_did_creator.go, pkg/did/trustbloc_did_creator_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> refactor: #169 rp-adapter: use public DIDs in didcomm invitations

cmd/adapter-rest/startcmd/start.go
=> feat: #182 configure logging level

pkg/restapi/internal/common/http/common.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> chore: [Issuer Adapter] Add log statements

cmd/adapter-rest/startcmd/start.go, test/bdd/features/healthcheck_api.feature, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] TLS Support

cmd/issuer-adapter-vue/package-lock.json, cmd/issuer-adapter-vue/package.json, cmd/issuer-adapter-vue/postcss.config.js, cmd/issuer-adapter-vue/src/App.vue, cmd/issuer-adapter-vue/src/assets/css/tailwind.css, cmd/issuer-adapter-vue/src/main.js, cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, cmd/issuer-adapter-vue/src/pages/layout/Footer.vue, cmd/issuer-adapter-vue/src/pages/layout/Layout.vue, cmd/issuer-adapter-vue/src/router/index.js, cmd/issuer-adapter-vue/tailwind.config.js
=> feat: [Issuer Adapter] UI Update

cmd/issuer-adapter-vue/public/index.html, cmd/rp-adapter-vue/public/index.html
=> fix: Update page titles

cmd/issuer-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json, cmd/rp-adapter-vue/postcss.config.js, cmd/rp-adapter-vue/src/App.vue, cmd/rp-adapter-vue/src/assets/css/tailwind.css, cmd/rp-adapter-vue/src/main.js, cmd/rp-adapter-vue/src/pages/Credentials.vue, cmd/rp-adapter-vue/src/pages/layout/Footer.vue, cmd/rp-adapter-vue/src/pages/layout/Layout.vue, cmd/rp-adapter-vue/src/router/index.js, cmd/rp-adapter-vue/tailwind.config.js
fixes #200 
<details><summary>Screenshot</summary>
</details>
=> fix: #200 rp adapter UI

cmd/rp-adapter-vue/postcss.config.js, cmd/rp-adapter-vue/src/assets/css/tailwind.css, cmd/rp-adapter-vue/tailwind.config.js
Fixes linting error: https://dev.azure.com/trustbloc/edge/_build/results?buildId=6148&view=results
=> fix: linting error

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
=> fix: [Issuer Adapter] Remove user button clicks during Wallet Connect

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/aries/api.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/didcomm/.env, test/bdd/go.mod, test/bdd/go.sum
=> refactor: Update adapter code based on latest aries-framework-go changes

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, go.mod, go.sum, pkg/db/rp/rp.go, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/adapter-rest/mysql-config/mysql_config.sql, test/bdd/go.mod, test/bdd/go.sum
=> fix: #216 use edge-core mysql storage

pkg/presentationex/api.go, pkg/presentationex/provider.go, pkg/presentationex/provider_test.go
=> feat: update to new presentation exchange

scripts/check_license.sh
=> fix: Exclude licence check in svg files

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations_test.go, pkg/restapi/rp/operation/testdata/context/authorization-credential-v1.jsonld, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/models.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/jsonld.go, test/bdd/pkg/rp/rp_steps.go, test/bdd/pkg/rp/testdata/context/authorization-credential-v1.jsonld
https://github.com/trustbloc/context/blob/master/vc/authorization-credential-v1.jsonld
closes #188 
=> refactor: Rename ConsentCredential to AuthorizationCredential

cmd/adapter-rest/startcmd/start.go, pkg/internal/mock/outofband/client.go, pkg/internal/mock/outofband/service.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/features/rp_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/rp/rp_steps.go
=> refactor: #225 use oob invitations instead of didexchange

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: go mod tidy

pkg/db/rp/models.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/rp/rp_steps.go
=> fix: [RP Adapter] Support to configure scopes

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml
=> feat: #236 configure database connection retries

cmd/adapter-rest/startcmd/start.go
=> feat: Configure governance vcs url in adapter cmd

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum
Update edge-core dependency (includes trustbloc/edge-core#52, trustbloc/edge-core#55)
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>
=> chore: Update edge-core dependency

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/governance/provider.go, pkg/governance/provider_test.go, pkg/internal/mock/governance/provider.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/integration/.env, test/bdd/fixtures/integration/docker-compose.yml, test/bdd/fixtures/integration/governance-vcs-profiles.sh
=> feat: Create governance vc through governance VCS

cmd/adapter-rest/startcmd/start_test.go, pkg/internal/common/adapterutil/adapterutil.go, pkg/presentationex/provider_test.go, pkg/presexch/api.go, pkg/presexch/api_test.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/testdata/presentationdefinitions.json, test/bdd/pkg/rp/rp_steps.go
=> fix: #256 presentation exchange schema URI should be an array

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go
=> feat: Configure token request parameter

go.sum, pkg/internal/mock/governance/provider.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/rp_steps.go
=> feat: Retrieve governance vc

test/bdd/cmd/issuer/main.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go
=> test: [Issuer Adapter] Update BDD tests to show support for multiple issuers

cmd/adapter-rest/startcmd/start.go
Since provider was assigned to a struct, the code panics when goverance url wasn't configured
=> fix: Assign governance provider to a interface rather than struct

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, cmd/issuer-adapter-vue/src/pages/components/Footer.vue, cmd/issuer-adapter-vue/src/pages/views/Landing.vue, cmd/issuer-adapter-vue/tailwind.config.js, cmd/rp-adapter-vue/src/pages/Credentials.vue, cmd/rp-adapter-vue/src/pages/components/Footer.vue, cmd/rp-adapter-vue/tailwind.config.js
closes #275
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>
=> fix: Issuer adapter chapi window loading fix and minor UI fix

pkg/restapi/issuer/operation/operations.go, pkg/restapi/rp/operation/operations.go
=> fix: change issue governance vc order

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, test/bdd/cmd/issuer/main.go
=> chore: [Issuer Adapter] Add credential name and description

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/rp_steps.go
=> refactor: use credentials in DIDconnect request to send gov vc

cmd/rp-adapter-vue/src/pages/Credentials.vue
=> fix: RP - sending credentials in didconnect CHAPI request

test/bdd/fixtures/integration/.env
=> chore: update vcs image

test/bdd/fixtures/did-trustbloc/.env
=> chore: update sidetree-mock to 0.1.4

README.md
=> fix: Update adapter azure pipeline link

ci/version_var.sh
=> chore: bump snapshot version to 0.1.5

test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go
=> test: [Issuer Adapter] Verify DID resolution before using it for signing

test/bdd/pkg/bddutil/util.go, test/bdd/pkg/rp/rp_steps.go
=> fix: [rp adapter bdd] Confirm Resolution of newly created DIDs before use

test/bdd/fixtures/adapter-rest/mysql-config/mysql_config.sql, test/bdd/fixtures/didcomm/.env, test/bdd/fixtures/didcomm/docker-compose.yml
=> chore: switch aries-agent to use MYSQL

pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
=> refactor: [Issuer Adapter] move common test code to a new file

.golangci.yml, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/did/trustbloc_did_creator.go, pkg/hydra/client.go, pkg/internal/common/adapterutil/adapterutil_test.go, pkg/presexch/api_test.go, pkg/restapi/rp/operation/credentials_test.go, scripts/check_lint.sh, test/bdd/dockerutil/compose.go, test/bdd/pkg/context/context.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/rp/jsonld.go, test/bdd/pkg/rp/rp_steps.go
=> chore: Upgrade golang-ci to v1.31.0

cmd/issuer-adapter-vue/package-lock.json, cmd/issuer-adapter-vue/package.json, cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json
=> fix: Upgrade node-forge and serialize-javascript (fix sec vulnerability)

cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, go.mod, go.sum, pkg/governance/provider.go, pkg/governance/provider_test.go, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/did-trustbloc/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/context/context.go, test/bdd/pkg/rp/rp_steps.go
=> chore: update trustbloc-did-method revision

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/message/models.go, pkg/message/msg_svc.go, pkg/message/msg_svc_test.go, pkg/message/service.go, pkg/message/service_test.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
- Integrate message svc and issuer
- Remove purpose
part of #340 
=> feat: Integrate Message service with Issuer Adapter

pkg/message/models.go, pkg/message/service.go, pkg/message/service_test.go, pkg/message/support_test.go, pkg/restapi/issuer/operation/operations.go
- Create connection with the didDoc passed as part of the request
closes #341 
=> feat: Routing - Handle Create Connection Req

pkg/internal/mock/mediator/client.go, pkg/message/service.go, pkg/message/service_test.go, pkg/message/support_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/fixtures/integration/.env, test/bdd/fixtures/integration/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/agent/msg_svc.go
=> feat: Blinded Routing - Router registration

test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/msg_svc.go
=> test: Update hub-router dependency

pkg/internal/mock/mediator/client.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/route/models.go, pkg/route/msg_svc.go, pkg/route/msg_svc_test.go, pkg/route/service.go, pkg/route/service_test.go, pkg/route/support_test.go, test/bdd/pkg/agent/msg_svc.go
=> feat: Blinded Routing - Support to use router's endpoint in AuthZCred

pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/route/service.go, pkg/route/service_test.go, pkg/route/support_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go
=> test: Blinded Routing - AuthZ bdd tests

cmd/adapter-rest/startcmd/start.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/rp/controller_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/restapi/rp/operation/support_test.go, pkg/route/service.go, pkg/route/service_test.go, pkg/route/support_test.go
=> feat: RP Adapter - Integrate Blinded Routing

docs/rp/README.md, docs/rp/integration/wallet_rpadapter_int_overview.puml, docs/rp/integration/wallets.md
closes #363 
Initial RPAdapter/wallet integration guide.
=> docs: #363 rpadapter/wallet integration

docs/rp/integration/wallets.md
=> fix: rpadapter-wallet integration docs image url

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
Disabled validation as this is not integrated in wallet yet.
unblocks https://github.com/trustbloc/edge-sandbox/pull/625
related to #373 
=> refactor: Disable rp authz did validation

docs/rp/integration/relying_parties.md
=> docs: #375 rp-adapter include `openid` in authz request

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/rp_steps.go
=> test: Blinded Routing - RP adapter bdd

pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/restapi/rp/operation/operations.go, pkg/route/service.go, pkg/route/service_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/issuer/issuer_steps.go
=> feat: [Issuer Adapter] Configuration for Blinded Routing feature

cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/did/trustbloc_did_creator.go, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/rp/rp_steps.go
Update sidetree, did-method, agent-sdk, vc services
Closes #382
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
=> chore: update sidetree, did-method, agent-sdk, vc services

pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/rp/operation/operations.go, pkg/route/service.go, test/bdd/features/issuer_e2e.feature, test/bdd/pkg/issuer/issuer_steps.go
Update following keys:
- SupportsAssuranceCredential -> supportsAssuranceCredential
- requiresBlindedRouting -> requiresBlindedRoute
=> refactor: Issuer profile - update json key

pkg/db/rp/models.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/rp/rp_steps.go
=> feat: RP Adapter - configure blinded route feat and add authz DID validation

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/restapi/rp/operation/testdata/context/authorization-credential-v1.jsonld, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, pkg/vc/models.go, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/jsonld.go, test/bdd/pkg/rp/rp_steps.go, test/bdd/pkg/rp/testdata/context/authorization-credential-v1.jsonld
=> refactor: AuthZ Credential - Add subjectDIDDoc

README.md, docs/blinded_routing.md, docs/issuer/issuer_integration.md, docs/rp/integration/relying_parties.md
=> docs: Blinded Routing

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/crypto/crypto.go, pkg/crypto/crypto_test.go, pkg/crypto/util.go, pkg/crypto/util_test.go, pkg/did/trustbloc_did_creator.go, pkg/did/trustbloc_did_creator_test.go, pkg/internal/mock/diddoc/diddoc.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/operations_test.go, pkg/vc/issuer/credentials_test.go, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/rp/rp_steps.go
=> chore: update aries-framework-go and did-method revision

test/bdd/features/rp_e2e.feature
=> chore: update rp tenant label

go.mod, go.sum, pkg/did/trustbloc_did_creator.go, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/rp/rp_steps.go
=> chore: update sidetree-mock and did-method

test/bdd/fixtures/integration/.env
=> chore: Hub-router docker update

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update aries, agent-sdk and hub-router dependencies

ci/version_var.sh
=> chore: release 0.1.5 complete

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, images/adapter-rest-base/Dockerfile, images/issuer-adapter-rest/Dockerfile, images/rp-adapter-rest/Dockerfile, test/bdd/fixtures/adapter-rest/.env, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/integration/.env, test/bdd/fixtures/integration/docker-compose.yml
=> ci: migrate to ghcr

README.md, ci/azure-pipelines.yml, docs/rp/integration/relying_parties.md, docs/rp/integration/wallets.md, docs/rp/protocols.md
=> chore: rename master branch to main

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, cmd/adapter-rest/startcmd/testdata/pres-def-mock.json, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go
=> feat: wallet bridge operations in adapter cmd

cmd/adapter-rest/startcmd/start.go, pkg/restapi/wallet/operation/models.go, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go, test/bdd/features/issuer_e2e.feature, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/agent/msg_svc.go, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/context/context.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/rp/rp_steps.go
=> feat: issuer wallet bridge bddtests

test/bdd/pkg/bddutil/util.go, test/bdd/pkg/common/wallet_steps.go
=> chore: wallet bridge bddtests - CHAPI resonse validation

cmd/wallet-js-client/package-lock.json, cmd/wallet-js-client/package.json
=> chore: marking wallet npm package as public

ci/azure-pipelines.yml
=> fix: NPM TAG version for wallet JS API

ci/azure-pipelines.yml
=> fix: npm publish settings

cmd/wallet-js-client/package.json
=> chore: wallet js client build

ci/azure-pipelines.yml, cmd/issuer-adapter-vue/.npmrc, cmd/issuer-adapter-vue/package-lock.json, cmd/issuer-adapter-vue/package.json, cmd/issuer-adapter-vue/src/main.js, cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, cmd/issuer-adapter-vue/vue.config.js, cmd/rp-adapter-vue/.npmrc, cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json, cmd/rp-adapter-vue/src/main.js, cmd/rp-adapter-vue/src/pages/Credentials.vue, cmd/rp-adapter-vue/vue.config.js
- removed direct dependency on credential handler polyfill(browser
wallet)
- Closes #426
=> feat: rp and issuer adapeters to use wallet client API

pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/wallet/operation/models.go, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go, pkg/restapi/wallet/operation/store.go, pkg/restapi/wallet/operation/store_test.go, test/mock/cmd/issuer/main.go
=> feat: wallet preference settings

cmd/wallet-js-client/package-lock.json, cmd/wallet-js-client/package.json, cmd/wallet-js-client/src/polyfill.js, cmd/wallet-js-client/src/remote.js, cmd/wallet-js-client/src/wallet-client.js, cmd/wallet-js-client/webpack.config.js, pkg/restapi/wallet/operation/models.go, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go, test/bdd/pkg/common/wallet_steps.go
=> feat: wallet client API - remote wallet support

cmd/issuer-adapter-vue/package-lock.json, cmd/issuer-adapter-vue/package.json, cmd/issuer-adapter-vue/src/pages/WalletConnect.vue, cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json, cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/issuer/operation/operations.go
=> feat: issuer adapter - webwallet client integration

cmd/wallet-js-client/src/index.js, cmd/wallet-js-client/src/wallet-client.js
- part of rp & issuer integration
- once merged, a new patchset for rp & issuer updates will be pushed
- part of #423
=> feat: wallet client integration with rp & issuer

cmd/issuer-adapter-vue/src/pages/WalletPreference.vue, cmd/rp-adapter-vue/src/pages/WalletPreference.vue, pkg/restapi/wallet/operation/operations.go, pkg/restapi/wallet/operation/operations_test.go, pkg/restapi/wallet/operation/store.go, pkg/restapi/wallet/operation/store_test.go
- rp & issuer QRcode scan & registration
- Closes #441
=> feat: remote wallet registration in adapters

.gitignore, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, go.mod, go.sum, pkg/profile/issuer/profile.go, pkg/restapi/internal/common/oidc/oidc.go, pkg/restapi/internal/common/oidc/oidc_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, scripts/generate_test_keys.sh, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/fixtures/adapter-rest/mysql-config/mysql_config.sql, test/bdd/fixtures/integration/.env, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> feat: register issuer oidc provider when registering issuer profile

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/presexch/api_test.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/vc/issuer/credentials.go, pkg/vc/issuer/credentials_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/rp/jsonld.go, test/bdd/pkg/rp/rp_steps.go
=> chore: update aries-framework-go revision

Makefile, ci/azure-pipelines.yml, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/restapi/internal/common/oidc/oidc.go, pkg/restapi/internal/common/oidc/oidc_test.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/oidc_operations.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, test/bdd/bddtests_test.go, test/bdd/dockerutil/docker.go, test/bdd/features/issuer_e2e_oidc.feature, test/bdd/fixtures/adapter-rest/.env, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go, test/mock/cmd/issuer-login-consent/go.mod, test/mock/cmd/issuer-login-consent/main.go, test/mock/images/issuer-login-consent/Dockerfile
=> feat: oidc integrated into request flows

pkg/restapi/internal/common/oidc/oidc.go, pkg/restapi/internal/common/oidc/oidc_test.go, pkg/restapi/issuer/operation/oidc_operations.go, pkg/restapi/issuer/operation/oidc_operations_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: avoid requesting reauthorization if access/refresh token exists.

ci/version_var.sh
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
=> chore: complete v0.1.6 release

cmd/issuer-adapter-vue/package-lock.json, cmd/issuer-adapter-vue/package.json, cmd/issuer-adapter-vue/vue.config.js, cmd/rp-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package.json, cmd/rp-adapter-vue/vue.config.js, pkg/profile/issuer/profile.go, pkg/restapi/internal/common/oidc/oidc.go, pkg/restapi/internal/common/oidc/oidc_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/oidc_operations.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/wallet/operation/operations_test.go, test/bdd/pkg/bddutil/util.go, test/mock/cmd/issuer/main.go
=> feat: issuer adapter uses access tokens scoped to the credential

ci/azure-pipelines.yml, ci/version_var.sh, cmd/wallet-js-client/package.json
=> chore: rename npm package

ci/azure-pipelines.yml, ci/version_var.sh, cmd/wallet-js-client/package.json
=> chore: rename npm package to wallet-adapter-web

pkg/presentationex/provider.go, pkg/presentationex/provider_test.go, test/bdd/fixtures/testdata/presentationdefinitions.json
=> fix: invalid pres-exch schema

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go
=> fix: Make TLS optional

pkg/jsonld/contexts/booking-reference-v1.jsonld, pkg/jsonld/contexts/w3id-citizenship-v1.jsonld, pkg/jsonld/contexts/w3id-vaccination-v1.jsonld, pkg/jsonld/loader.go
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> chore: add extra contexts

cmd/adapter-rest/startcmd/start.go, pkg/jsonld/loader.go
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> fix: missing document loader for presentproof service

cmd/adapter-rest/startcmd/start.go, pkg/did/trustbloc_did_creator.go, pkg/did/trustbloc_did_creator_test.go
=> chore: add requet token for vdr

pkg/did/trustbloc_did_creator.go, test/bdd/pkg/rp/rp_steps.go
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>
=> feat: JsonWebKey2020 support

cmd/issuer-adapter-vue/package-lock.json, cmd/rp-adapter-vue/package-lock.json, cmd/wallet-adapter-web/package-lock.json, docs/build.md, go.mod, test/bdd/go.mod
=> chore: update npm to v7

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/rp/rp_steps.go
=> feat: WACI - support to generate OOB message

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, pkg/restapi/rp/operation/support_test.go, test/bdd/pkg/agent/agent_controller_steps.go
=> feat: waci/present-proof - handle proposal message and send request message

cmd/adapter-rest/startcmd/start.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/rp/operation/operations.go
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> fix: multiple JSON-LD loaders

cmd/rp-adapter-vue/src/pages/Credentials.vue, docs/rp/integration/wallets.md
- update presentation exchange query from RP
=> feat: update to universal wallet query format

pkg/restapi/rp/operation/credentials.go, pkg/restapi/rp/operation/credentials_test.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: waci - validate presentation

.github/workflows/build.yml
=> ci: fix publish job

.github/workflows/build.yml, Makefile
=> ci: add tags to github actions

.github/workflows/build.yml
=> ci: publish - fix docker secret variable

README.md, images/adapter-rest-base/Dockerfile, images/issuer-adapter-rest/Dockerfile, images/rp-adapter-rest/Dockerfile
=> chore: README file update with changed repo name

.github/workflows/build.yml
=> fix: typo in build name

pkg/restapi/rp/operation/operations.go, test/bdd/features/rp_e2e.feature, test/bdd/pkg/rp/rp_steps.go
- Unmarshal presentation
- Retrieve user data and pass it as OIDC claims
closes #515 
=> feat: waci - retrieve user data from presentation

.github/workflows/build.yml
=> ci: update repo name

pkg/restapi/rp/operation/operations.go, test/bdd/pkg/agent/agent_controller_steps.go
=> fix: rp request presentation message format

cmd/rp-adapter-vue/src/pages/Credentials.vue
=> feat: waci response handler in rp view

cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/restapi/rp/operation/operations.go
=> fix: waci integration issues

cmd/adapter-rest/startcmd/start.go, cmd/rp-adapter-vue/src/pages/Credentials.vue, pkg/db/rp/models.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/fixtures/adapter-rest/docker-compose.yml, test/bdd/pkg/rp/rp_steps.go
- for WACI redirect & QR code flow
=> feat: linked wallet feature rp adapter

pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go
=> feat: rp - retry on user credential collection data

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-trustbloc/.env, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
=> chore: update latest bdd tests refs

ci/version_var.sh, test/bdd/fixtures/integration/.env
=> chore: release 0.1.7

pkg/restapi/issuer/operation/operations.go
=> chore: [issuer oidc] log error message

pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
=> feat: Issuer Adapter - waci flow support during profile creation

test/bdd/features/issuer_e2e_waci.feature, test/bdd/pkg/issuer/issuer_steps.go
=> test: [issuer] waci support during profile creation

pkg/restapi/issuer/operation/oidc_operations.go, pkg/restapi/issuer/operation/oidc_operations_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
Update code to set oidcProviderURL instead of issuerID.
closes #552 
=> fix: [issuer] odic provider url

cmd/issuer-adapter-vue/src/pages/WalletConnect.vue
- first time wallet selection was causing JS error sometimes and was
blocking CHAPI wallet selection
=> fix: issuer browser wallet selection issue

.github/workflows/build.yml, Makefile, cmd/adapter-rest/go.mod, docs/build.md, go.mod, test/bdd/go.mod, test/mock/cmd/issuer-login-consent/go.mod, test/mock/cmd/issuer/go.mod, test/mock/cmd/webhook/go.mod
=> chore: golang v1.17 update

pkg/profile/issuer/profile.go, pkg/profile/issuer/profile_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go
=> fix: Update profile issuer id to be not mandatory

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, cmd/adapter-rest/startcmd/start.go, go.mod, go.sum, pkg/did/trustbloc_did_creator.go, pkg/internal/mock/outofbandv2/service.go, pkg/profile/issuer/profile.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, test/bdd/features/waci_didcommv2.feature, test/bdd/fixtures/integration/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/agent_controller_steps.go, test/bdd/pkg/agent/wallet.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: WACI issuance integration with DIDComm v2

pkg/restapi/issuer/operation/operations.go
=> fix: WACI issuance - credential manifest attachment

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update afgo version

pkg/restapi/issuer/operation/operations.go
=> fix: add format to IssueCredentialParams

cmd/adapter-rest/startcmd/start.go, cmd/adapter-rest/startcmd/start_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
closes #563
BDD Test will be covered in #595 
=> feat: Support for presentation exchange

docs/build.md
=> docs: update build pre-requisites

pkg/db/rp/models.go, pkg/profile/issuer/profile.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/issuer/operation/support_test.go, pkg/restapi/rp/operation/models.go, pkg/restapi/rp/operation/operations.go, pkg/restapi/rp/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/rp/rp_steps.go
=> fix: add DIDcommv1 flag

cmd/issuer-adapter-vue/src/pages/GeneralError.vue, cmd/issuer-adapter-vue/src/router/index.js, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: WACI Issuance failure error screen

test/bdd/fixtures/testdata/manifest-config/cmdescriptors.json
=> test: update credential manifest config for prc

ci/version_var.sh
=> chore: v0.1.8 release complete

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest aries

cmd/adapter-rest/go.mod, cmd/adapter-rest/go.sum, go.mod, go.sum, pkg/did/trustbloc_did_creator.go, pkg/did/trustbloc_did_creator_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/route/support_test.go, test/bdd/features/waci_didcommv2.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/agent/wallet.go
To line up with the latest Credential Manifest spec.
Also made some minor updates to KMS interface code due to changes in aries-framework-go.
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>
=> feat: Change Credential Fulfillment to Credential Response

.github/workflows/build.yml, .gitignore
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
=> ci: add semantic commit check

cmd/adapter-rest/startcmd/start.go
=> chore: add did web

cmd/adapter-rest/startcmd/start.go
=> fix: did web
